version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/usk81/ashihara/shared"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/usk81/ashihara/service/holidays"
